#ifndef MYST_H_INCLUDED
#define MYST_H_INCLUDED

#include <iostream>
#include <string>
#include <vector>
#include <fstream>
#include <ctime>
#include <cstdlib>

/** getDico
 * \brief Gets the words from a file into a vector of strings
 * \param dico the vector which has to contain the words
 * \param inFile the path to the file
 */
void getDico(std::vector<std::string>& dico, std::string const& inFile);


/** chooseWord
 * \brief picks a random word in a vector of strings
 * \param dico the vector which has to contain the words
 * \returns a word of dico
 */
std::string chooseWord(std::vector<std::string> const& dico);

/** shuffleWord
 * \brief shuffles the letters of a word in order to create a new word
 * \param word a string whose characters have to be shuffled
 * \returns a string with the same characters in a different order
 */
std::string shuffleWord(std::string word);

/** guessWord
 * \brief ask the user to guess the word whose letters have been shuffled
 * \param original a string to guess
 * \param shuffled the string with shuffled letters (generated by shuffleWord)
 */
void guessWord(std::string original, std::string shuffled);

/** oneMore
 * \brief ask the user if he wants to play again
 * \returns a bolean, true to play again, false to stop the game
 */
bool oneMore();

#endif